import Navigation from "@/components/layout/Navigation";
import type { Metadata } from "next";
import "./globals.css";
import Toast from "@/components/ui/Toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Navigation />
        {children}
        <Toast />
      </body>
    </html>
  );
}
